### ISSUE TITLE
example results?

### ISSUE THREAD

**Issue by jinfagang** [fishaudio/fish-diffusion#1]

**Comment by leng-yue** [comment]
Here it is:

https://drive.google.com/file/d/1PbYH8t5ZB73hfVz466x9NGzpe3agigCz/view?usp=share_link

The above result was obtained with the following setup:
- A 2.5 hours private singing dataset.
- Two 3090 for ~4 hours. 
- Config file: svc_hubert_soft.py

I trained the model for 10 more hours, which has a more stable loudness.  
If you attach a vocal-only sound, I can also convert it for you.
