### ISSUE TITLE
Cannot import name 'HiFiSingerV1Lightning'

### ISSUE THREAD

**Issue by ayu2hami** [fishaudio/fish-diffusion#107]
On google colab and locally on my pc, I get this error while trying to use inference. In this situation I tried use HiFiSinger.
Quick note, 2-3 days ago I didn't had this problem.

Traceback (most recent call last):
  File "/content/fish-diffusion/tools/hifisinger/inference.py", line 13, in <module>
    from fish_diffusion.archs.hifisinger import HiFiSingerV1Lightning, HiFiSingerV2Lightning
ImportError: cannot import name 'HiFiSingerV1Lightning' from 'fish_diffusion.archs.hifisinger' (unknown location)

also this while trying to infer with diffusion:

Traceback (most recent call last):
  File "/content/fish-diffusion/tools/diffusion/inference.py", line 23, in <module>
    from fish_diffusion.utils.inference import load_checkpoint
  File "/content/fish-diffusion/fish_diffusion/utils/inference.py", line 3, in <module>
    from fish_diffusion.archs.diffsinger import DiffSingerLightning
ImportError: cannot import name 'DiffSingerLightning' from 'fish_diffusion.archs.diffsinger' (unknown location)

**Comment by LordElf** [comment]
Checkout the release/mmengine-fish-v2 branch and it should work:) We just converted all the configs to yaml and will no longer use mmengine.
