### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here   in "/content/fish-diffusion/configs/svc_hifisinger_finetune.py", line 11, column 18

### ISSUE THREAD

**Issue by chigkim** [fishaudio/fish-diffusion#113]
I get this error when I try to run on Colab notebook.
`!python tools/preprocessing/extract_features.py --clean --num-workers 4 "{config_path}"`
[svc_hifisinger_finetune.py.txt](https://github.com/fishaudio/fish-diffusion/files/12187760/svc_hifisinger_finetune.py.txt)

**Comment by leng-yue** [comment]
Sorry for the confusing, there are some issue in the latest version of fish-diffusion, and we plan to rollback soon.
