### ISSUE TITLE
Google colab pyworld problem

### ISSUE THREAD

**Issue by ayu2hami** [fishaudio/fish-diffusion#114]
Using google colab I cant make it work... it gives me this error when I try to install dependencies:

> Successfully installed: PDM (2.8.1) at /root/.local/bin/pdm
Post-install: Please add /root/.local/bin to PATH by executing:
    export PATH=/root/.local/bin:$PATH
Inside an active virtualenv /content/env/envs/fish_diffusion, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
⠸ Fetching hashes for resolved packages...
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

>   ✖ Install pyworld 0.3.3 failed
> Retry failed jobs
>   ✖ Install pyworld 0.3.3 failed

> ERRORS:
add pyworld failed:
Traceback (most recent call last):
  File 
"/content/env/envs/fish_diffusion/lib/python3.10/concurrent/futures/thread.py", 
line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchro
nizers.py", line 277, in install_candidate
    self.manager.install(can)
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager
.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.
py", line 393, in build
    self.wheel = Path(builder.build(build_dir, 
metadata_directory=self._metadata_dir))
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/wheel.py"
, line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, 
metadata_directory)
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.
py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.
py", line 311, in _call_hook
    self._subprocess_runner(
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py",
line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File 
"/root/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py",
line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines
of the build output:
    yield from chunks
  File "/content/env/envs/fish_diffusion/lib/python3.10/json/encoder.py", line 
405, in _iterencode_dict
    yield from chunks
  File "/content/env/envs/fish_diffusion/lib/python3.10/json/encoder.py", line 
325, in _iterencode_list
    yield from chunks
  File "/content/env/envs/fish_diffusion/lib/python3.10/json/encoder.py", line 
438, in _iterencode
    o = _default(o)
  File "/content/env/envs/fish_diffusion/lib/python3.10/json/encoder.py", line 
179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable

> See /tmp/pdm-install-2hoker48.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

and then after this if I try to Extract features for the audio files it gives me this error:

> Traceback (most recent call last):
  File "/content/fish-diffusion/tools/preprocessing/extract_features.py", line 18, in <module>
    from fish_diffusion.modules.energy_extractors import ENERGY_EXTRACTORS
ModuleNotFoundError: No module named 'fish_diffusion'
Traceback (most recent call last):
  File "/content/fish-diffusion/tools/preprocessing/extract_features.py", line 18, in <module>
    from fish_diffusion.modules.energy_extractors import ENERGY_EXTRACTORS
ModuleNotFoundError: No module named 'fish_diffusion'

**Comment by leng-yue** [comment]
I will take a look.

**Comment by leng-yue** [comment]
This is fixed in the latest version. Feel free to reopen issue if meeting again.
