### ISSUE TITLE
Type of pitches during the training of nsf_hifigan

### ISSUE THREAD

**Issue by wblgers** [fishaudio/fish-diffusion#115]
Hi, 

Thanks for sharing your work. I want to figure out the type of input pitches during the training of nsf_hifigan. It's continuouse pitch or the raw pitch extracted from ParselMouth.

Thanks!

**Comment by leng-yue** [comment]
It's extracted from ParselMouth, and then upsampled to audio length.

**Comment by wblgers** [comment]
> It's extracted from ParselMouth, and then upsampled to audio length.
Oh, let me clarify my question as below:
On line 75 of tools/diffusion/inference.py
`if pitches is None:
            pitches = self.pitch_extractor(audio, sr, pad_to=mel_len).float()`
pad_to-mel_len means the 0 pitches are removed and linear interpolated. 
Is there the same preprocess during the training of nsf_hifigan?

**Comment by leng-yue** [comment]
It depends on whether you enable keep zeros in pitch extractor or not...

**Comment by wblgers** [comment]
> It depends on whether you enable keep zeros in pitch extractor or not...


Oh, I made a mistake. Yes, It depends on keep_zeros when construct pitch_extractor.
1. Since the pretrained model of vocoder nsf_hifigan is provided, can you remember whether keep_zeros is enable or not in the training of pretrained nsf_hifigan? 
2. Do you compare the vocoder performance between the training configured as keep_zeros enbaled or disabled?
3. Will the mismatch of acoustic model and vocoder on keep_zeros lead to performance degradation?

**Comment by leng-yue** [comment]
keep_zeros is generally better and thus we enabled it.

**Comment by wblgers** [comment]
Thanks for your explaination!
