### ISSUE TITLE
Recent commit breaks poetry install for me

### ISSUE THREAD

**Issue by dillfrescott** [fishaudio/fish-diffusion#16]
The commit:

https://github.com/fishaudio/fish-diffusion/commit/e460e38f75e2639a1b0584852d869cd966205ad9

Seems to cause `poetry install` to throw an error about groups...

**Comment by leng-yue** [comment]
Can you try the latest update? Can you paster your poetry error log here if it doesn't work?

**Comment by dillfrescott** [comment]
Tried the latest commit as of this comment. Still throwing the error sadly.

```
RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/local/envs/fish/lib/python3.10/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
ERROR conda.cli.main_run:execute(47): `conda run poetry install` failed. (See above for error)
```

**Comment by dillfrescott** [comment]
Anything before commit https://github.com/fishaudio/fish-diffusion/commit/e460e38f75e2639a1b0584852d869cd966205ad9 works fine

**Comment by leng-yue** [comment]
Can you check your poetry version? Poetry < 1.2.0 probably doesn't work.

**Comment by dillfrescott** [comment]
So apparently i was using an older version of poetry. But when I try with a newer version it just says:

```
Installing dependencies from lock file

Package operations: 149 installs, 4 updates, 0 removals

ERROR conda.cli.main_run:execute(47): `conda run poetry install` failed. (See above for error)
```

**Comment by leng-yue** [comment]
Uninstall your poetry, and use pip to install again :)

**Comment by dillfrescott** [comment]
Okay

**Comment by leng-yue** [comment]
Feel free to reopen the issue if you have any problem :)
