### ISSUE TITLE
does this support amd gpus if not how do i use this with google collab

### ISSUE THREAD

**Issue by Pickymarker** [fishaudio/fish-diffusion#17]
does this support amd gpus if not how do i use this with google collab

**Comment by leng-yue** [comment]
- The code theoretically supports AMD GPUs but has not been tested yet. If you have programming experience, we are happy to merge pull requests :)
- Some devs are working on the Colab notebook (probably this or next week), please follow.

**Comment by Pickymarker** [comment]
because i want to be able to easily do something like diff svc with a amd gpu and does the code for this use cuda and tensorflow if so then not amd compatible

**Comment by leng-yue** [comment]
It doesn't need hard code .cuda, and it uses PyTorch... Please at least read a few lines of code before submitting issues...

**Comment by leng-yue** [comment]
You can apply for English Notebook in the discord channel now.
