### ISSUE TITLE
預處理出現 No module named 'fish_audio_preprocess' 錯誤

### ISSUE THREAD

**Issue by seq2193** [fishaudio/fish-diffusion#28]
不論有沒有使用 CONDA 都出現錯誤
就算使用 https://mirrors.aliyun.com/pypi/simple/fish-audio-preprocess/ 安裝 pip install  xxx.whl 也是一樣的情況
不知有沒有辦法解決  謝謝!
![596](https://user-images.githubusercontent.com/109962092/220617621-c78f7e2e-c34e-4a50-8eeb-839491e728ba.PNG)

**Comment by leng-yue** [comment]
看起来你环境都没 activate, 建议重新 follow 下 notebook 的流程...
