### ISSUE TITLE
colab 微调训练那裏出錯

### ISSUE THREAD

**Issue by seq2193** [fishaudio/fish-diffusion#30]
![87](https://user-images.githubusercontent.com/109962092/221587027-72008ccb-777e-41e8-8e96-559434601395.PNG)
预训练模式有跑通,但是下一步 微调训练那裏出錯
IsADirectoryError: [Errno 21] Is a directory: '/content/fish-diffusion/checkpoints'

![88](https://user-images.githubusercontent.com/109962092/221586681-038ef462-84b0-45bb-a87f-d18eaaa74a41.PNG)

請問該如何解決? 謝謝

**Comment by Mixomo** [comment]
Same error here!

**Comment by seq2193** [comment]
您是指这个ckpt 文件吗？
https://github.com/fishaudio/fish-diffusion/releases/tag/v1.11 

[cn-hubert-soft-600-singers-pretrained-v1.ckpt](https://github.com/fishaudio/fish-diffusion/releases/download/v1.11/cn-hubert-soft-600-singers-pretrained-v1.ckpt)

**Comment by seq2193** [comment]
成功了 謝謝
但是發現一個問題就是 svc_cn_hubert_soft_finetune.py  無法產生 npy 文件
用 svc_hubert_soft.py 才能產生 npy 文件

![89](https://user-images.githubusercontent.com/109962092/221845427-1be899df-2078-4280-8505-744b77b92f0f.PNG)

**Comment by leng-yue** [comment]
额.. 你看看 wiki, 两个指定的训练文件夹不一样, 你要改一下.
