### ISSUE TITLE
一些关于增强的问题&bug反馈

### ISSUE THREAD

**Issue by Stardust-minus** [fishaudio/fish-diffusion#33]
1.目前的几个pitch增强 相对效果最好的哪个，以及是否可以给一个推荐的参数？
2.今天尝试用之前的config推理的时候发现爆炸了，求问是否有解决办法
![image](https://user-images.githubusercontent.com/52093397/222868825-094a588d-ec15-4a19-8ff3-30df4ebc5fca.png)
配置文件位于 https://paste.ubuntu.com/p/KWMsjKcGHp/
3.在使用多worker预处理时，如果机器上没有whisper模型，在尝试下载时会每个worker下载一遍，有些浪费
期待您的回复

**Comment by leng-yue** [comment]
1. 推荐 FixedPitchShifting 和 RandomPitchShifting, 推荐配置见 DiffSinger (
2. 配置文件需要修改
```python
model = dict(
    ...
    diffusion=dict(
        spec_min=[0] * 128,
        spec_max=[0] * 128,
    )
)
```
3. 这确实是个问题, 目前可以先用单 worker 下载下... 也可以考虑加个判断...

**Comment by Stardust-minus** [comment]
get
