### ISSUE TITLE
多节点集群训练问题

### ISSUE THREAD

**Issue by Stardust-minus** [fishaudio/fish-diffusion#35]
如题。
我在一个有4个节点，每个节点有8张GPU的集群上尝试训练。
其中trainer的配置已被修改，并且训练正常启动，读取到了32个RANK
![image](https://user-images.githubusercontent.com/52093397/223736059-3ac4863b-7b14-4655-9aab-7f1be1ee2aa7.png)
但我观察到，尽管每个节点上的单Epoch 的batch减少了，但step计算没有同步。
![image](https://user-images.githubusercontent.com/52093397/223736693-21012b2f-73dc-483e-92de-b97866eb6fe5.png)
在此情况下，运行到额定steps需要的Epoch更多，请问这是否会对收敛造成影响？
我应当使用steps计算还是Epoch？

**Comment by leng-yue** [comment]
这是 DDP 常见问题了, 你可能需要调整学习率和步数来适应多节点.  
其实多卡也是一样的, 因为每个卡的工作是独立的, 你卡越多, 一个 batch 跑的也就越快 (相当于你的实际 batch size 是原本的x卡数).

**Comment by Stardust-minus** [comment]
踩坑完毕，验证圆满完成（

**Comment by Stardust-minus** [comment]
一些经验
lr不推荐调的特别大，否则loss可能会震荡下不来（两轮不下降基本上可以remake
decay仍然是有必要的，可以设置一个比较恰当的min lr，全程大学习率对于收敛速度帮助似乎不是特别大，最后还是要小火慢炖
以及 目前多卡训练会每个节点均创建一个wandb log session 虽然可以添加 --tensor board参数 但是还是可以考虑在这里加个判定
