### ISSUE TITLE
Specify pytorch version for conda

### ISSUE THREAD

**Issue by Kickbub** [fishaudio/fish-diffusion#38]
Default pytorch is now 2.0 so we should specify that we want 1.13.1.

`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`

**Comment by Kickbub** [comment]
I followed the instructions on Windows and it said something like "Can't find cuda runtime using CUDA_HOME...". However I already had Cuda installed.

Does conda install cuda runtimes for you do you need to install it from nvidia as well?

**Comment by leng-yue** [comment]
conda will do that for you.

**Comment by Kickbub** [comment]
Also why does poetry reinstall torch?

**Comment by leng-yue** [comment]
Maybe some dependency caused that? We may need to debug the lock file...

**Comment by leng-yue** [comment]
We should probably install torch==1.13.1 as many dependencies didn't upgrade to torch 2.0 yet.
