### ISSUE TITLE
2.0版本如何套用预训练模型 content-vec-pretrained-v1.ckpt ？

### ISSUE THREAD

**Issue by seq2193** [fishaudio/fish-diffusion#43]
1.12 colab中 
python tools/diffusion/train.py --tensorboard --config configs/svc_cn_hubert_soft_finetune.py --pretrained {底模保存的目录} 
可以运用 /content/fish-diffusion/checkpoints/content-vec-pretrained-v1.ckpt  此ckpt

但是在2.0 中
python tools/diffusion/train.py --config configs/svc_content_vec.py  --pretrained {底模保存的目录}
似乎不行运用 /content/fish-diffusion/checkpoints/content-vec-pretrained-v1.ckpt
测试用 --resume xxx.ckpt 好像也不行
请问如何解决？谢谢！

**Comment by leng-yue** [comment]
正确做法应该是 
```bash
python tools/diffusion/train.py --tensorboard --config configs/svc_content_vec_finetune.py --pretrained checkpoints/content-vec-pretrained-v1.ckpt
```
pretrained 应该指向具体文件, 而不是文件夹.  
如果有报错麻烦上传下截图 (

**Comment by seq2193** [comment]
出現這個錯誤
![45](https://user-images.githubusercontent.com/109962092/227717794-0a0527fc-a07e-484f-884b-2749423158d1.PNG)
AssertionError: class `ConcatDataset` in fish_diffusion/datasets/concat.py: class `NaiveSVCDataset` in fish_diffusion/datasets/naive.py: No files found in dataset/train/lengyue, please check your path.

**Comment by seq2193** [comment]
还是出现错误无法训练 https://colab.research.google.com/drive/1mFBIYJkNdze-G95xHl2eAKuTfgayBPlK?usp=sharing

**Comment by leng-yue** [comment]
你要修改下配置文件中的 dataset 指向

**Comment by seq2193** [comment]
你是說修改這個文件? svc_content_vec_finetune.py

**Comment by leng-yue** [comment]
嗯嗯

**Comment by leng-yue** [comment]
咋样

**Comment by seq2193** [comment]
推理也可以了，可以关闭问题了，谢谢！
