### ISSUE TITLE
版本依赖很多低于Python3.10，为啥作者要求版本是Python3.10？

### ISSUE THREAD

**Issue by mzawdx2022** [fishaudio/fish-diffusion#44]
ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement praat-parselmouth==0.5.0 (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2.post2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3)
ERROR: No matching distribution found for praat-parselmouth==0.5.0

以上是  pip install -r requirements.txt结果。试了v1.12  v2.0.0  以及最新main都一样

**Comment by leng-yue** [comment]
这可能是 requirements.txt 的问题... 你试试 poetry?

**Comment by leng-yue** [comment]
我去确认了下, https://pypi.org/project/praat-parselmouth/0.4.3/#files 里面是有的, 是不是你用的镜像翻车了 😂

<img width="826" alt="image" src="https://user-images.githubusercontent.com/25119060/227758526-d2cdf266-0424-4072-8031-9f5c57c8c470.png">

**Comment by mzawdx2022** [comment]
> 我去确认了下, https://pypi.org/project/praat-parselmouth/0.4.3/#files 里面是有的, 是不是你用的镜像翻车了 😂
> 
> <img alt="image" width="826" src="https://user-images.githubusercontent.com/25119060/227758526-d2cdf266-0424-4072-8031-9f5c57c8c470.png">

这个是0.4.3版本，提示出错额是没有0.5.0版本

**Comment by leng-yue** [comment]
[praat-parselmouth==0.4.3](https://github.com/fishaudio/fish-diffusion/blob/b624578f360652f5f8e0c23fec89035d8c5d138c/requirements.txt#L60)

真的不知道你这个 0.5.0 是咋出来的 (

**Comment by mzawdx2022** [comment]
> 这可能是 requirements.txt 的问题... 你试试 poetry?

换了poetry这个就好了，pip那个太迷了，不纠结了。

**Comment by leng-yue** [comment]
okok
