### ISSUE TITLE
inference报错

### ISSUE THREAD

**Issue by mzawdx2022** [fishaudio/fish-diffusion#46]
![1](https://user-images.githubusercontent.com/128947045/227829488-ff23f111-a9d1-4db9-bef6-fa9b92b0adea.png)

按照“Quick FishSVC Guide”做下来，训练了10000多个steps, 推理测试了下报错。

感觉是训练的模型和推理的模型尺寸不匹配的问题，，，

**Comment by leng-yue** [comment]
你需要将 config 换成你训练的 config

**Comment by leng-yue** [comment]
1. 你可能要改到最新版, 这块是已经修了的
```python
try:
    speaker_id = self.config.speaker_mapping[speaker]
except (KeyError, AttributeError):
    # Parse speaker id
    speaker_id = int(speaker)
```

2. 1W 在没有预训练的情况远远不够, 考虑 20w+

**Comment by mzawdx2022** [comment]
> 1. 你可能要改到最新版, 这块是已经修了的
> 
> 
> ```python
> try:
>     speaker_id = self.config.speaker_mapping[speaker]
> except (KeyError, AttributeError):
>     # Parse speaker id
>     speaker_id = int(speaker)
> ```
> 
>     2. 1W 在没有预训练的情况远远不够, 考虑 20w+

嗯~ 我用的是v2.0.0，我用main主干的去试试看。

**Comment by mzawdx2022** [comment]
> 1. 你可能要改到最新版, 这块是已经修了的
> 
> 
> ```python
> try:
>     speaker_id = self.config.speaker_mapping[speaker]
> except (KeyError, AttributeError):
>     # Parse speaker id
>     speaker_id = int(speaker)
> ```
> 
>     2. 1W 在没有预训练的情况远远不够, 考虑 20w+

另外，大佬你在国内吗？ 能加个V不？ 我看了你代码，跟其他几个项目比较了下，你的代码质量非常高，想跟你更深入交流学习下。 感谢~

**Comment by leng-yue** [comment]
如果没有 inference 报错解决了我就先关闭 issue 了, 有问题你随时打开.
