### ISSUE TITLE
Train whisper on multilingual dataset

### ISSUE THREAD

**Issue by leng-yue** [fishaudio/fish-diffusion#5]
What will happen? We will use the MFA model to generate a calibrated dataset and be used to train whisper.

Chinese Dataset
- [x] Opencpop
- [x] M4Singer
- [x] OpenSinger
- [x] AIShell

English Dataset
- [x] LibriSpeech (train-clean-100h) 
- [x] LJSpeech

Japanese Dataset
- [ ] JSUT
- [ ] [Kokoro Speech](https://github.com/kaiidams/Kokoro-Speech-Dataset)
- [ ] [Namine Ritsu (NNSVS)](https://drive.google.com/file/d/1Nv3qwZ6DSr80W9qcV9ZBg5urKFtcdPp5/view?usp=drivesdk) This dataset is hard to preprocess, but its quality is good....

Dictionaries
- US: [arpabet](https://mfa-models.readthedocs.io/en/latest/dictionary/English/English%20%28US%29%20ARPA%20dictionary%20v2_0_0.html)
- JP: UNCLEAR (need to retrain the MFA model?)
- CN: OpenCpop Strict (OpenVPI)

**Comment by leng-yue** [comment]
Chinese Whisper is now available in v1.2 beta0

**Comment by leng-yue** [comment]
We need at least 30 English and Japanese hours of singing data to get a good model. Hope someone can collaborate :)

**Comment by KakaruHayate** [comment]
> We need at least 30 English and Japanese hours of singing data to get a good model. Hope someone can collaborate :)

Single speaker?

**Comment by leng-yue** [comment]
Multi-Speaker :)

**Comment by leng-yue** [comment]
This issue will be reopen once we have time.

**Comment by SpikeParaffa** [comment]
I'm impressed with your code.
But can you also add Korean for me?
I beg you.
