### ISSUE TITLE
请问 2.1 预处理的指令为何？

### ISSUE THREAD

**Issue by seq2193** [fishaudio/fish-diffusion#55]
请问与2.0预处理是通用吗？

python tools/preprocessing/extract_features.py --config configs/svc_content_vec.py --path dataset/train --clean
python tools/preprocessing/extract_features.py --config configs/svc_content_vec.py --path dataset/valid --clean --no-augmentation

**Comment by leng-yue** [comment]
一样的, 改成对应的 config 就行.

**Comment by seq2193** [comment]
# Process the training data (with augmentation if included in the config)
python tools/preprocessing/extract_features.py --config configs/svc_content_vec.py --path dataset/train --clean

# Process the validation data without augmentation
python tools/preprocessing/extract_features.py --config configs/svc_content_vec.py --path dataset/valid --clean --no-augmentation

請問是要把svc_content_vec.py 改成這樣?
python tools/preprocessing/extract_features.py --config configs/svc_hifisinger.py --path dataset/train --clean
python tools/preprocessing/extract_features.py --config configs/svc_hifisinger.py --path dataset/valid --clean --no-augmentation

**Comment by leng-yue** [comment]
嗯, 用预训练的话就下载 release 里面的

**Comment by Yurzi** [comment]
能问下 如何是svc_hifisinger.py要多人的话，就直接照着wiki中的那个multi-speaker的改就是了吧？
还有如果是使用预训练集的话，大概需要跑多少步？（每个speaker大概有1500条语音）

**Comment by leng-yue** [comment]
是的. 目前看来多跑点没啥坏处, 网络容量没那么大, 基本不会过拟合.
