### ISSUE TITLE
使用预训练模型中断后恢复训练时使用" --resume logs\**\**\checkpoints\**.ckpt"是否正确？

### ISSUE THREAD

**Issue by mikotorz** [fishaudio/fish-diffusion#56]
或者说应该继续使用" --pretrained logs\**\**\checkpoints\**.ckpt"？

**Comment by seq2193** [comment]
全新预模型训练方法为 --pretrained checkpoints/content-vec-pretrained-v1.ckpt

继续训练方法为 svc_content_vec_finetune.py --resume xxx.ckpt

**Comment by leng-yue** [comment]
正确的, 中肯的, 一针见血的 👍
