### ISSUE TITLE
checkpoint is not saved while training the mode in fish-diffusion-2.1.0

### ISSUE THREAD

**Issue by chandrakanthlns** [fishaudio/fish-diffusion#67]
/root/anaconda3/envs/fish/lib/python3.10/site-packages/lightning_fabric/plugins/io/torch_io.py:61: UserWarning: Warning, `hyper_parameters` dropped from checkpoint. An attribute is not picklable: Can't pickle local object 'EvaluationLoop.advance.<locals>.batch_to_device'
  rank_zero_warn(f"Warning, `{key}` dropped from checkpoint. An attribute is not picklable: {err}")

**Comment by Kickbub** [comment]
You can ignore this warning message.
