### ISSUE TITLE
training error in custom datasets

### ISSUE THREAD

**Issue by DonkeyHang** [fishaudio/fish-diffusion#77]
hi

I followed readme.md and prepared custom datasets, I don't see from the readme where the dataset folder should be placed so I guess dataset folder should be placed in root right? 

and then I prepared 3 speakers wav in train/vaild folder, modified config files in svc_hubert_soft_multi_speakers.py

> `from fish_diffusion.datasets.naive import NaiveSVCDataset
> 
> _base_ = [
>     "./svc_hubert_soft.py",
> ]
> 
> dataset = dict(
>     train=dict(
>         _delete_=True,  # Delete the default train dataset
>         type="NaiveSVCDataset",
>         datasets=[
>             dict(
>                 type="NaiveSVCDataset",
>                 path="dataset/train/speaker0",
>                 speaker_id=0,
>             ),
>             dict(
>                 type="NaiveSVCDataset",
>                 path="dataset/train/speaker1",
>                 speaker_id=1,
>             ),
>             dict(
>                 type="NaiveSVCDataset",
>                 path="dataset/train/speaker2",
>                 speaker_id=2,
>             ),
>         ],
>         # Are there any other ways to do this?
>         collate_fn=NaiveSVCDataset.collate_fn,
>     ),
>     valid=dict(
>         type="NaiveSVCDataset",
>         datasets=[
>             dict(
>             type="NaiveSVCDataset",
>             path="dataset/valid/speaker0",
>             speaker_id=0,
>             ),
>             dict(
>             type="NaiveSVCDataset",
>             path="dataset/valid/speaker1",
>             speaker_id=1,
>             ),
>             dict(
>             type="NaiveSVCDataset",
>             path="dataset/valid/speaker2",
>             speaker_id=2,
>             )
>         ]
>     )
> )
> 
> model = dict(
>     speaker_encoder=dict(
>         input_size=3,  # 3 speakers
>     ),
> )

`

and then execute command:python tools/diffusion/train.py --config configs/svc_hubert_soft_multi_speakers.py

but i got error:

> wandb: Currently logged in as: donkeyddddd. Use `wandb login --relogin` to force relogin

> wandb: WARNING Path logs\wandb\ wasn't writable, using system temp directory.
> wandb: WARNING Path logs\wandb\ wasn't writable, using system temp directory
> wandb: wandb version 0.15.0 is available!  To upgrade, please run:
> wandb:  $ pip install wandb --upgrade
> wandb: Tracking run with wandb version 0.13.11
> wandb: Run data is saved locally in C:\Users\DONKEY~1\AppData\Local\Temp\wandb\run-20230423_220917-i34fcjr1
> wandb: Run `wandb offline` to turn off syncing.
> wandb: Syncing run curious-cherry-8
> wandb:  View project at https://wandb.ai/donkeyddddd/DiffSVC
> wandb:  View run at https://wandb.ai/donkeyddddd/DiffSVC/runs/i34fcjr1
> Using 16bit None Automatic Mixed Precision (AMP)
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> Traceback (most recent call last):
>   File "C:\Users\donkeyddddd\anaconda3\envs\fish_diffusion\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
>     obj = obj_cls(**args)  # type: ignore
> TypeError: NaiveDataset.__init__() got an unexpected keyword argument 'datasets'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\python_projects\git_projects\fish-diffusion\tools\diffusion\train.py", line 97, in <module>
>     train_loader, valid_loader = build_loader_from_config(cfg, trainer.num_devices)
>   File "D:\python_projects\git_projects\fish-diffusion\fish_diffusion\datasets\utils.py", line 13, in build_loader_from_config
>     train_dataset = DATASETS.build(cfg.dataset.train)
>   File "C:\Users\donkeyddddd\anaconda3\envs\fish_diffusion\lib\site-packages\mmengine\registry\registry.py", line 521, in build
>     return self.build_func(cfg, *args, **kwargs, registry=self)
>   File "C:\Users\donkeyddddd\anaconda3\envs\fish_diffusion\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
>     raise type(e)(
> TypeError: class `NaiveSVCDataset` in fish_diffusion/datasets/naive.py: NaiveDataset.__init__() got an unexpected keyword argument 'datasets'
> wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
> wandb:  View run curious-cherry-8 at: https://wandb.ai/donkeyddddd/DiffSVC/runs/i34fcjr1
> wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
> wandb: Find logs at: C:\Users\DONKEY~1\AppData\Local\Temp\wandb\run-20230423_220917-i34fcjr1\logs

Can you give me some suggestions and ways to solve this problem?

**Comment by Majboor** [comment]
hmm. I think there is an issue with the `NaiveSVCDataset`  class

**Comment by DonkeyHang** [comment]
> hmm. I think there is an issue with the `NaiveSVCDataset` class

maybe, 
for the same ways i executed so-vits-svc and it's work well

**Comment by leng-yue** [comment]
To avoid errors, it is recommended not to use the `NaiveSVCDataset` with the datasets argument. Instead, please refer to the [multispeaker training config](https://github.com/fishaudio/fish-diffusion/blob/main/configs/svc_hubert_soft_multi_speakers.py), which utilizes the `ConcatDataset` to concatenate multiple `NaiveSVCDataset`.
