### ISSUE TITLE
Help with v2.1 training 

### ISSUE THREAD

**Issue by AppleSeed03** [fishaudio/fish-diffusion#78]
![image](https://user-images.githubusercontent.com/47828184/233863935-b7312771-101e-4b84-bb5f-c0182275f6c1.png)
While v2.0 works just fine, when switch to v2.1, I encountered error message shown above.
Same error message occurs if  de-novo training instead of fine-tuning are used.
Any idea on how to fix that?
Thanks!

**Comment by leng-yue** [comment]
Consider using `python tools/hifisinger/train.py` instead, as the HiFiSinger architecture does not rely on diffusion. For additional examples and information, please refer to the notebook. If you have any questions regarding training, feel free to reopen this issue.
