### ISSUE TITLE
Does training with Multi Speakers improve model quality to generalize better and handle variety inputs?

### ISSUE THREAD

**Issue by chigkim** [fishaudio/fish-diffusion#79]
Does training with Multi Speakers improve model quality to generalize better handle variety of unseen input sources?
Or, it just lets you inference to different speaker?

**Comment by Majboor** [comment]
recognize and generalize differences between voices.

**Comment by chigkim** [comment]
Thanks. Does it have impact on quality of output when processing variety of unseen input sources?

**Comment by Majboor** [comment]
multiple set of speakers =   better learning to recognize and generate this way the model is more representative of natural language use.
