### ISSUE TITLE
Dealing with Scratchy Output and Octave Shift?

### ISSUE THREAD

**Issue by chigkim** [fishaudio/fish-diffusion#81]
I have two problems that I often encounter, and I wonder if anyone has suggestion.

1. Output audio with scratchy parts
2. Some pitches get shifted either one octave lower or higher than the source

I'm attaching a sample output only highlighting the problems.
Thanks!
[Scratchy.zip](https://github.com/fishaudio/fish-diffusion/files/11349679/Scratchy.zip)

**Comment by chigkim** [comment]
I'm just using the default configuration from svc_hifisinger_finetune.py.

```
    pitch_extractor=dict(
        type="ParselMouthPitchExtractor",
        keep_zeros=False,
        f0_min=40.0,
        f0_max=1600.0,
    ),
```

**Comment by leng-yue** [comment]
Try CrepePitchExtractor when your input quality is not that good.
