### ISSUE TITLE
Fish Diffusion 对 SVS 的支持

### ISSUE THREAD

**Issue by lvZic** [fishaudio/fish-diffusion#82]
请问下，这类项目包括diff-svc 主要做的工作是歌曲音色转换，那diff-singer就是输入歌词+乐曲生成歌曲的工作，你们工程里不包含这一部分是吗

**Comment by leng-yue** [comment]
包含, 见 configs/svs

**Comment by lvZic** [comment]
> 包含, 见 configs/svs

感谢回复
我看了下configs目录下的文件 svs部分有使用文档吗 类似这种https://github.com/MoonInTheRiver/DiffSinger/blob/master/docs/README-SVS.md

我现在用到的svs结果是三方数据库训练好的歌手声音，我是想把svs 和 svc串起来，转换一下音色

**Comment by lvZic** [comment]
> 目前没有, 这块还在开发 (

ok 期待
