### ISSUE TITLE
Having issue with basic install

### ISSUE THREAD

**Issue by megablocks** [fishaudio/fish-diffusion#98]
After going through installation instructions - git pull and pdm sync, any command I try to run I am getting following error " from fish_diffusion.archs.diffsinger.diffsinger import DiffSingerLightning
ModuleNotFoundError: No module named 'fish_diffusion'"

Not sure how to go past this.

**Comment by leng-yue** [comment]
Can you try pdm install?

**Comment by megablocks** [comment]
fish-diffusion>pdm install
All packages are synced to date, nothing to do.
Installing the project as an editable package...
  v Update fish-diffusion 2.2.0+editable -> 2.2.0 successful

  All complete!

fish-diffusion\tools\diffusion\inference.py", line 17, in <module>
    from fish_diffusion.archs.diffsinger.diffsinger import DiffSingerLightning
ModuleNotFoundError: No module named 'fish_diffusion'

**Comment by leng-yue** [comment]
Did you activate the pdm env? ususally in `.venv`

**Comment by leng-yue** [comment]
Closed due to inactive
